bootstrap_common: &bootstrap_common
  pull: true

    
build_common: &build_common
  commands:
    - mkdir -p /opt/metwork-mfcom-${DRONE_BRANCH}
    - make
    - make doc
    - rm -Rf html_doc
    - cp -Rf /opt/metwork-mfcom-${DRONE_BRANCH}/html_doc .
    - make test
    - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
    - mv /opt/metwork-mfcom-${DRONE_BRANCH}/*.rpm .  
    
publish_ci_common: &publish_ci_common
  commands:
    - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - yum -y install createrepo
    - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
    - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom/ ; fi
  volumes:
    - /pub:/pub
  
pipeline:
  bootstrap_integration:
    <<: *bootstrap_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    commands:
      - mkdir -p /opt/metwork-mfcom-${DRONE_BRANCH}
      - ./bootstrap.sh /opt/metwork-mfcom-${DRONE_BRANCH} /opt/metwork-mfext-integration
      - cat adm/root.mk
    when:
      event: [push, pull_request]
      branch: integration
  bootstrap:
    <<: *bootstrap_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:master
    commands:
      - mkdir -p /opt/metwork-mfcom-${DRONE_BRANCH}
      - ./bootstrap.sh /opt/metwork-mfcom-${DRONE_BRANCH} /opt/metwork-mfext-master
      - cat adm/root.mk
    when:
      event: [push, pull_request]
      branch:
        exclude: [ integration ]  
  build_integration:
    <<: *build_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    when:
      event: [push, pull_request]
      branch: integration
  build:
    <<: *build_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:master
    when:
      event: [push, pull_request]
      branch:
        exclude: [ integration ]  
  publish_ci_integration:
    <<: *publish_ci_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    when:
      event: [push]
      branch: integration
  publish_ci:
    <<: *publish_ci_common
    image: metwork/mfcom-${OS_VERSION}-buildimage:master
    when:
      event: [push]
      branch:
        exclude: [ integration ]

matrix:
  OS_VERSION:
    - centos6
    - centos7
