pipeline:
  bootstrap:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    pull: true
    commands:
      - mkdir -p /opt/metwork-mfcom-${DRONE_BRANCH}
      - ./bootstrap.sh /opt/metwork-mfcom-${DRONE_BRANCH} /opt/metwork-mfext-${DRONE_BRANCH}
      - cat adm/root.mk
    when:
      event: [push]
  build:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - mkdir -p /opt/metwork-mfcom-${DRONE_BRANCH}
      - make
      - make doc
      - rm -Rf html_doc
      - cp -Rf /opt/metwork-mfcom-${DRONE_BRANCH}/html_doc .
      - make test
      - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
      - mv /opt/metwork-mfcom-${DRONE_BRANCH}/*.rpm .
    volumes:
      - /buildcache:/buildcache
    when:
      event: [push]
  publish_ci:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - yum -y install createrepo
      - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
      - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfcom/ ; fi
    volumes:
      - /pub:/pub
    when:
      event: [push]

matrix:
  OS_VERSION:
    - centos6
    - centos7
